version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    command: ["sh", "-c", "sleep 20 && /portainer -H unix:///var/run/docker.sock"]

volumes:
  portainer_data:
