version: '3'

services:
  portainer:
    image: registry.cloud.okteto.net/keteda7894/portainer-portainer:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - ADMIN_PASSWORD=poorimontrashcan

volumes:
  portainer_data:
