services:
  portainer:
    image: portainer/portainer-ce:latest
    command:
      - -H tcp://0.0.0.0:2375
    environment:
      - ADMIN_PASSWORD=poorimontrashcan
      - TZ=America/Vancouver
    volumes:
      - name: portainer-data
        hostPath:
          path: /data/portainer
    ports:
      - 9000:9000
    sync:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data:
